esphome:
  name: "hdmi-cec-demo"

external_components:
  - source:
      type: local
      path: components

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

# Enable OTA
ota:
  password: !secret mgmt_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:

hdmi_cec:
  pin: GPIO26
  address: 0x5
  physical_address: 0x4000
  on_message:
    # Volume Up
    - data: [0x44, 0x41]
      then:
        logger.log: "Volume Up"

    # Volume Down
    - data: [0x44, 0x42]
      then:
        logger.log: "Volume Down"

    # Mute
    - data: [0x44, 0x43]
      then:
        - logger.log: "Mute"
